config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :kadyot do
    resources :clients
    resources :prices
    resources :accounts do
      collection do
        post  'search'
        post  'search_by_name'
        post  'search_by_month'
        get   'print'
        get   'generate_pdf'
        get   'print_sales_report'
        get   'latest_summary_report'
        get   'get_totals'
        get   'get_search_client'
      end
    end
  end

  namespace :sagad do
    resources :clients
    resources :prices
    resources :accounts do
      collection do
        post  'search'
        post  'search_by_name'
        post  'search_by_month'
        get   'print'
        get   'generate_pdf'
        get   'print_sales_report'
        get   'latest_summary_report'
        get   'get_totals'
        get   'get_search_client'
      end
    end
  end

  namespace :viral do
    resources :clients
    resources :prices
    resources :accounts do
      collection do
        post  'search'
        post  'search_by_name'
        post  'search_by_month'
        get   'print'
        get   'generate_pdf'
        get   'print_sales_report'
        get   'latest_summary_report'
        get   'get_totals'
        get   'get_search_client'
      end
    end
  end

  namespace :kilatis do
    resources :clients
    resources :prices
    resources :accounts do
      collection do
        post  'search'
        post  'search_by_name'
        post  'search_by_month'
        get   'print'
        get   'generate_pdf'
        get   'print_sales_report'
        get   'latest_summary_report'
        get   'get_totals'
        get   'get_search_client'
      end
    end
  end


  resources :reports do
    collection do
      post  'generate'
    end
  end

  devise_for :users
  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
    authenticated :user do
      root 'sagad/clients#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  root 'sagad/clients#index'

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/new',   to: 'users#new',   via: 'get'
  match '/users/:id/edit',   to: 'users#edit',   via: 'get',   as: 'edit_user'
  match '/users/create',   to: 'users#create',   via: 'post'
  match '/users/:id',   to: 'users#show',   via: 'get',   as: 'user'
  match '/users/:id',   to: 'users#update',   via: 'patch'
  match '/users/:id',   to: 'users#update',   via: 'put'
  match '/users/:id',   to: 'users#destroy',   via: 'delete'

end

app/controllers/kadyot/accounts_controller.rb
module Kadyot
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    helper_method :grey_page
    layout "print_layout", :only => [ :print, :print_sales_report ]

    # GET /accounts
    # GET /accounts.json
    def index
      @client = KadyotClient.order("lname ASC, fname ASC").first
      @accounts = KadyotAccount.where(:id_client => @client.id, :yr => @year_today, :mon => @month_today).order("day ASC")
      @selected_month = @month_today
      @selected_year = @year_today
      get_latest_account(@client.id)
    end
    # GET /accounts/1
    # GET /accounts/1.json
    def show
    end

    # GET /accounts/new
    def new
      @client = KadyotClient.find(params[:id])
      @accounts = KadyotAccount.where(:id_client => @client.id, :yr => params[:yr], :mon => params[:mon]).order("day ASC")
      @selected_month = params[:mon]
      @selected_year = params[:yr]
      get_latest_account(@client.id)
      @account = KadyotAccount.new
    end

    # GET /accounts/1/edit
    def edit
      @client = KadyotClient.find(@account.id_client)
      @accounts = KadyotAccount.where("id != #{@account.id} AND id_client = #{@client.id} AND yr = #{@account.yr} AND mon = #{@account.mon}").order("day ASC")
      @selected_month = @account.mon
      @selected_year = @account.yr
      get_latest_account(@client.id)
    end

    # POST /accounts
    # POST /accounts.json
    def create
      @account = KadyotAccount.new(account_params)
      @account.user_id = session[:user_logged_id]
      @client = KadyotClient.find(@account.id_client)
      @accounts = KadyotAccount.where(:id_client => @client.id, :yr => @account.yr, :mon => @account.mon).order("day ASC")
      @selected_month = @account.mon
      @selected_year = @account.yr
      get_latest_account(@client.id)
      if @account.save
        render "index"
      else
        render "new"

      end
    end

    # PATCH/PUT /accounts/1
    # PATCH/PUT /accounts/1.json
    def update
      @account.user_id = session[:user_logged_id]
      @client = KadyotClient.find(@account.id_client)
      @accounts = KadyotAccount.where(:id_client => @client.id, :yr => @account.yr, :mon => @account.mon).order("day ASC")
      @selected_month = @account.mon
      @selected_year = @account.yr
      get_latest_account(@client.id)
      if @account.update(account_params)
        render "index"
      else
        render "edit"
      end
    end

    # DELETE /accounts/1
    # DELETE /accounts/1.json
    def destroy
      @client = KadyotClient.find(@account.id_client)
      @accounts = KadyotAccount.where(:id_client => @client.id, :yr => @account.yr, :mon => @account.mon).order("day ASC")
      @selected_month = @account.mon
      @selected_year = @account.yr
      get_latest_account(@client.id)

      archive_account = KadyotArchiveAccount.new
      archive_account.id = @account.id
      archive_account.id_client = @account.id_client
      archive_account.yr = @account.yr
      archive_account.mon = @account.mon
      archive_account.day = @account.day
      archive_account.po = @account.po
      archive_account.re = @account.re
      archive_account.sold = @account.sold
      archive_account.price = @account.price
      archive_account.tcash = @account.tcash
      archive_account.tamount = @account.tamount
      archive_account.bal = @account.bal
      archive_account.date_paid = @account.date_paid
      archive_account.paid = @account.paid
      archive_account.bank_name = @account.bank_name
      archive_account.check_num = @account.check_num
      archive_account.date_issued = @account.date_issued
      archive_account.rsnum = @account.rsnum
      archive_account.prnum = @account.prnum
      archive_account.user_id = session[:user_logged_id]
      archive_account.save

      @account.destroy
      render "index"

    end

    def search
      @date = Date.today
      @client = KadyotClient.find(params[:id_client])
      @accounts = KadyotAccount.where(:id_client => params[:id_client], :yr => @year_today, :mon => @month_today).order("day ASC")
      @selected_month = @month_today
      @selected_year = @year_today
      get_latest_account(@client.id)
      render "index"
    end

    def search_by_name
      @date = Date.today
      @client = KadyotClient.where(:lname => params[:lname], :fname => params[:fname]).first
      @accounts = KadyotAccount.where(:id_client => @client.id, :yr => @year_today, :mon => @month_today).order("day ASC")
      @selected_month = @month_today
      @selected_year = @year_today
      get_latest_account(@client.id)
      render "index"
    end

    def search_by_month
      @client = KadyotClient.find(params[:client_id])
      @accounts = KadyotAccount.where("id_client = #{params[:client_id]} AND yr = #{params[:yr]} AND mon = #{params[:mon]}").order("yr DESC, mon DESC, day ASC")
      @selected_month = params[:mon]
      @selected_year = params[:yr]
      get_latest_account(@client.id)
      render "index"
    end


    def print
      @client = KadyotClient.find(params[:id])
      @accounts = KadyotAccount.select("*, IFNULL(STR_TO_DATE(date_paid,'%m/%d/%Y'), CAST(date_paid AS DATE)) as latest_date_paid").where("id_client = #{params[:id]} AND yr = #{params[:yr]} AND mon = #{params[:mon]}").order("yr DESC, mon DESC, day ASC")
      @account_mon_sum = KadyotAccount.select("SUM(po) AS po, SUM(re) AS re, SUM(sold) AS sold, SUM(tamount) AS tamount, SUM(tcash) AS tcash, SUM(bal) AS bal").where("id_client = #{params[:id]} AND yr = #{params[:yr]} AND mon = #{params[:mon]}")
      @account_overall_sum =  KadyotAccount.select("SUM(bal) AS bal").where("id_client = #{params[:id]}")
      @selected_month = params[:mon]
      @selected_year = params[:yr]
    end

    def print_sales_report
      @accounts = KadyotAccount.select("
                    CONCAT(kadyot_clients.lname, ', ', kadyot_clients.fname) as client_name,
                    SUM(po) AS po,
                    SUM(re) AS re,
                    SUM(sold) AS sold,
                    SUM(tamount) AS tamount,
                    SUM(tcash) AS tcash,
                    SUM(bal) AS bal
                  ").joins("
                    LEFT JOIN kadyot_clients ON kadyot_clients.id = kadyot_accounts.id_client
                  ").where("
                    yr = #{params[:yr]}
                    AND mon = #{params[:mon]}
                  ").group("
                    id_client
                  ").order("
                    CONCAT(kadyot_clients.lname, ', ', kadyot_clients.fname) ASC
                  ")
      @account_mon_sum = KadyotAccount.select("SUM(po) AS po, SUM(re) AS re, SUM(sold) AS sold, SUM(tamount) AS tamount, SUM(tcash) AS tcash, SUM(bal) AS bal").where("yr = #{params[:yr]} AND mon = #{params[:mon]}")
      @account_overall_sum =  KadyotAccount.select("SUM(bal) AS bal")
      @selected_month = params[:mon]
      @selected_year = params[:yr]
    end

    def latest_summary_report
      @accounts = KadyotAccount.select("
                    CONCAT(kadyot_clients.lname, ', ', kadyot_clients.fname) as client_name,
                    SUM(po) AS po,
                    SUM(re) AS re,
                    SUM(sold) AS sold,
                    SUM(tamount) AS tamount,
                    SUM(tcash) AS tcash,
                    SUM(bal) AS bal,
                    (SELECT STR_TO_DATE(date_paid,'%m/%d/%Y') FROM kadyot_accounts AS temp_accounts WHERE temp_accounts.id_client = kadyot_accounts.id_client ORDER BY STR_TO_DATE(temp_accounts.date_paid,'%m/%d/%Y') DESC LIMIT 1) as date_paid
                  ").joins("
                    LEFT JOIN kadyot_clients ON kadyot_clients.id = kadyot_accounts.id_client
                  ").where("
                    yr = #{params[:yr]}
                    AND mon = #{params[:mon]}
                  ").group("
                    id_client
                  ").order("
                    CONCAT(kadyot_clients.lname, ', ', kadyot_clients.fname) ASC,
                    date_paid DESC
                  ")
      @account_mon_sum = KadyotAccount.select("SUM(po) AS po, SUM(re) AS re, SUM(sold) AS sold, SUM(tamount) AS tamount, SUM(tcash) AS tcash, SUM(bal) AS bal").where("yr = #{params[:yr]} AND mon = #{params[:mon]}")
      @account_overall_sum =  KadyotAccount.select("SUM(bal) AS bal")
      @selected_month = params[:mon]
      @selected_year = params[:yr]

    end

    def generate_pdf
      @clients = KadyotClient.all.order("lname ASC, fname ASC")
      @accounts = KadyotAccount.select("*, IFNULL(STR_TO_DATE(date_paid,'%m/%d/%Y'), CAST(date_paid AS DATE)) as latest_date_paid").where("yr = #{params[:yr]} AND mon = #{params[:mon]}").order("yr DESC, mon DESC, day ASC")
      @account_mon_sum = KadyotAccount.select("SUM(po) AS po, SUM(re) AS re, SUM(sold) AS sold, SUM(tamount) AS tamount, SUM(tcash) AS tcash, SUM(bal) AS bal, id_client").where("yr = #{params[:yr]} AND mon = #{params[:mon]}").group("id_client")
      @account_overall_sum = KadyotAccount.select("SUM(po) AS po, SUM(re) AS re, SUM(sold) AS sold, SUM(tamount) AS tamount, SUM(tcash) AS tcash, SUM(bal) AS bal, id_client").group("id_client")
      respond_to do |format|
        format.html{ render :nothing => true }
        format.pdf do
          pdf = Prawn::Document.new(:page_layout => :landscape, :page_size => 'A2')

          @clients.each do |client|
            pdf.font_size 20
            pdf.text "Kadyot / JV-GO PUBLISHING HOUSE INC.", :align => :center
            pdf.move_down 30
            pdf.text "#{client.lname}, #{client.fname} #{client.mi}", :align => :left
            pdf.text "#{client.address}", :align => :left
            pdf.move_down 30
            pdf.font_size 16
            pdf.text "Data:", :align => :left
            pdf.font_size 12
            accounts = [["Day", "P.O", "Re", "Sold", "Price", "T.Amount", "T.Cash", "Bal", "D.Paid", "Paid", "Type", "Bank Name", "#", "Issued", "R.S. #", "P.R. #"]]

app/controllers/sagad/clients_controller.rb
module Sagad
  class ClientsController < ApplicationController
    before_action :set_client, only: [:show, :edit, :update, :destroy]
    # GET /clients
    # GET /clients.json
    def index
      @clients = SagadClient.all
    end

    # GET /clients/1
    # GET /clients/1.json
    def show
    end

    # GET /clients/new
    def new
      @client = SagadClient.new
    end

    # GET /clients/1/edit
    def edit
    end

    # POST /clients
    # POST /clients.json
    def create
      @client = SagadClient.new(client_params)

      respond_to do |format|
        if @client.save
          format.html { redirect_to @client, notice: 'Client was successfully created.' }
          format.json { render :show, status: :created, location: @client }
        else
          format.html { render :new }
          format.json { render json: @client.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /clients/1
    # PATCH/PUT /clients/1.json
    def update
      respond_to do |format|
        if @client.update(client_params)
          format.html { redirect_to @client, notice: 'Client was successfully updated.' }
          format.json { render :show, status: :ok, location: @client }
        else
          format.html { render :edit }
          format.json { render json: @client.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /clients/1
    # DELETE /clients/1.json
    def destroy
      archive_client = SagadArchiveClient.new
      archive_client.id = @client.id
      archive_client.lname = @client.lname
      archive_client.fname = @client.fname
      archive_client.mi = @client.mi
      archive_client.pnum = @client.pnum
      archive_client.tnum = @client.tnum
      archive_client.user_id = session[:user_logged_id]
      archive_client.save
      @client.destroy
      respond_to do |format|
        format.html { redirect_to sagad_clients_url, notice: 'Client was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = SagadClient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:sagad_client).permit(:lname, :fname, :mi, :pnum, :tnum, :address)
    end
  end

end

app/controllers/sagad/prices_controller.rb
module Sagad
  class PricesController < ApplicationController
    before_action :set_price, only: [:show, :edit, :update, :destroy]
    # GET /prices
    # GET /prices.json
    def index
      @prices = SagadPrice.order("price DESC")
    end

    # GET /prices/1
    # GET /prices/1.json
    def show
    end

    # GET /prices/new
    def new
      @price = SagadPrice.new
    end

    # GET /prices/1/edit
    def edit
    end

    # POST /prices
    # POST /prices.json
    def create
      @price = SagadPrice.new(price_params)

      respond_to do |format|
        if @price.save
          format.html { redirect_to @price, notice: 'Price was successfully created.' }
          format.json { render :show, status: :created, location: @price }
        else
          format.html { render :new }
          format.json { render json: @price.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /prices/1
    # PATCH/PUT /prices/1.json
    def update
      respond_to do |format|
        if @price.update(price_params)
          format.html { redirect_to @price, notice: 'Price was successfully updated.' }
          format.json { render :show, status: :ok, location: @price }
        else
          format.html { render :edit }
          format.json { render json: @price.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /prices/1
    # DELETE /prices/1.json
    def destroy
      @price.destroy
      respond_to do |format|
        format.html { redirect_to sagad_prices_url, notice: 'Price was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = SagadPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:sagad_price).permit(:price)
    end
  end
end

app/views/sagad/accounts/_process.html.erb
<style>
  div.link a:visited {
    color: #dd8b00!important;
  }
  div.link a {
    text-decoration: underline;
  }
  @media (max-width: 767px) {
    label {
      text-align: left!important;
    }
  }
  label {
    text-align: right;
  }
</style>
<!-- begin page-header -->
<div class="header-darkblue">
  <h1 class="pull-left">
    <%= render 'layouts/static/header', header_title: "#{format_client_name(@client.lname, @client.fname)}", sub_header_title: ((@latest_account && !@latest_account.latest_date_paid.nil? && @latest_account.latest_date_paid.present? && !@latest_account.latest_date_paid.blank?) ? "| Latest Date Paid: #{@latest_account.latest_date_paid.to_date.strftime('%m/%d/%Y')}" : "") + (@latest_account ? " | Encoded Date Paid: #{@latest_account.mon}/#{@latest_account.day}/#{@latest_account.yr}" : "") %>
  </h1>
  <span class="pull-right">

    <%= link_to 'Latest Summary Report', latest_summary_report_sagad_accounts_path(mon: @selected_month, yr: @selected_year), :class => "btn btn-green btn-xs"   %>
    <%= link_to 'Print Sales Report', print_sales_report_sagad_accounts_path(mon: @selected_month, yr: @selected_year), :class => "btn btn-indigo btn-xs"   %>&nbsp;|&nbsp;
    <%= link_to 'Refresh', sagad_accounts_path, :class => "btn btn-secondary btn-xs" %>
    <%= link_to 'PDF', generate_pdf_sagad_accounts_path(:pdf, mon: @selected_month, yr: @selected_year), :class => "btn btn-success btn-xs" %>
    <%= link_to 'Print', print_sagad_accounts_path(id: @client, mon: @selected_month, yr: @selected_year), :class => "btn btn-danger btn-xs"   %>
    <button type="button" class="btn btn-purple btn-xs" id="sagad_search">Search Client</button>
    <button type="button" class="btn btn-lime btn-xs" id="sagad_show_totals" data-client_id="<%= @client.id %>" data-selected_year="<%= @selected_year %>" data-selected_month="<%= @selected_month %>">Show Totals</button>
    <%= link_to 'New Account', new_sagad_account_path(id: @client, mon: @selected_month, yr: @selected_year), :class => "btn btn-primary btn-xs" %>
  </span>
</div>
<!-- end page-header -->
<!-- begin panel -->
<%= render 'modals' %>
<div class="panel panel-inverse">
  <div class="panel-heading">
    <h4 class="panel-title">
      &nbsp;
      <span class="pull-left">
        <%= form_tag search_by_name_sagad_accounts_path do %>
            <%= text_field_tag :lname, nil, placeholder: "Last Name" %>
            <%= text_field_tag :fname, nil, placeholder: "First Name" %>
          <%= submit_tag 'Search by Name', :class => "btn btn-primary btn-xs" %>
      <% end %>
      </span>
      <span class="pull-right">
      <%= form_tag search_by_month_sagad_accounts_path do %>
        <%= hidden_field_tag :client_id, @client.id %>
          <%= select_tag :mon, options_for_select([ ['January', 1], ['February', 2], ['March', 3], ['April', 4], ['May', 5], ['June', 6], ['July', 7], ['August', 8], ['September', 9], ['October', 10], ['November', 11], ['December', 12]], @selected_month), include_blank: "", :class => 'search-keypress' %> -
          <%= number_field_tag :yr, @selected_year %>&nbsp;
          <%= submit_tag 'Search Date', :class => "btn btn-info btn-xs" %>
      <% end %>
    </span>
    </h4>
  </div>
  <div class="panel-body">
    <%= render 'table'%>

  </div>
</div>

<!-- end panel -->



app/views/sagad/accounts/_table.html.erb
<h4>Accounts</h4>
<div class="scroll-me">
  <table class="table table-striped table-bordered display nowrap">
    <thead>
    <tr>
      <th>Day</th>
      <th>PO</th>
      <th>Re</th>
      <th>Re%</th>
      <th>Sold</th>
      <th>Sales%</th>
      <th>Price</th>
      <th>T.Amount</th>
      <th>T.Cash</th>
      <th>Bal.</th>
      <th>Date paid</th>
      <th>Paid</th>
      <th>Type</th>
      <th>B.Name</th>
      <th>Check #</th>
      <th>D.Issued</th>
      <th>RS #</th>
      <th>PR #</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% if params[:action] == "new" %>
      <%= form_for(@account) do |f| %>
        <%= f.hidden_field :yr, :value => @selected_year %>
        <%= f.hidden_field :mon, :value => @selected_month %>
        <%= f.hidden_field :id_client, :value => @client.id %>
        <tr>
          <td><%= f.number_field :day, :class => "form-control adjust-input-width" %></td>
          <td><%= f.number_field :po, :class => "form-control adjust-input-width" %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td> <%= f.submit "Save", :class => "btn btn-primary btn-xs" %></td>
          <td><%= link_to 'Back', sagad_accounts_path, :class => "btn btn-danger btn-xs" %></td>

        </tr>
      <% end %>
    <% elsif params[:action] == "edit" %>
      <%= form_for(@account) do |f| %>
        <tr>
          <td><%= @account.day %></td>
          <td><%= @account.po %><%= f.hidden_field :po, id: "account_po", :value => @account.po, :class => "form-control adjust-input-width" %></td>
          <td><%= f.number_field :re, id: "account_re", :class => "form-control adjust-input-width" %></td>
          <td></td>
          <td><%= f.text_field :sold, id: "account_sold", :readonly => true, :class => "form-control adjust-input-width "%></td>
          <td></td>
          <td><%= f.select :price, @prices.collect { |s| [s.price, s.price] }, {prompt: 'Select'}, :class => "form-control adjust-input-width", id: "account_price" %></td>
          <td><%= f.text_field :tamount, id: "account_tamount", :readonly => true, :class => "form-control adjust-input-width", :step => 'any' %></td>
          <td><%= f.number_field :tcash, id: "account_tcash", :class => "form-control adjust-input-width", :step => 'any' %></td>
          <td><%= f.text_field :bal, id: "account_bal", :readonly => true, :class => "form-control adjust-input-width", :step => 'any' %></td>
          <td><%= f.text_field :date_paid, class: 'form-control  adjust-input-width datepicker-autoClose', 'data-inputmask' => "'alias': 'mm/dd/yyyy'", value: get_date_format(@account.date_paid) %></td>
          <td><%= f.check_box :paid %></td>
          <td><%= f.select :payment_type, options_for_select(['Full', 'Partial', 'w/ Balance'], @account.payment_type),{:include_blank => true}, class: 'form-control adjust-input-width' %></td>
          <td><%= f.text_field :bank_name, :class => "form-control adjust-input-width" %></td>
          <td><%= f.text_field :check_num, :class => "form-control adjust-input-width" %></td>
          <td><%= f.date_field :date_issued, :class => "form-control", value: @account.date_issued ? @account.date_issued.to_date.strftime('%Y-%m-%d').to_s : '' %></td>
          <td><%= f.text_field :rsnum, :class => "form-control adjust-input-width" %></td>
          <td> <%= f.text_field :prnum, :class => "form-control adjust-input-width" %></td>
          <td><button type="submit" name="commit" value="" class="btn btn-success btn-xs"><i class="fas fa-save"></i></button></td>
          <td><a class="btn btn-danger btn-xs" href="<%= sagad_accounts_path %>"><i class="fa fa-ban" aria-hidden="true"></i></a></td>

        </tr>
      <% end %>
    <% end %>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.day %></td>
        <td><%= account.po %></td>
        <td><%= account.re %></td>
        <td><b><%= get_return_percentage(account.po, account.re) %>%</b></td>
        <td><%= account.sold %></td>
        <td><b><%= get_sale_percentage(account.po, account.re) %>%</b></td>
        <td><%= account.price %></td>
        <td><%= account.tamount %></td>
        <td><%= account.tcash %></td>
        <td><b><%= account.bal %></b></td>
        <td><%= get_date_format(account.date_paid) %></td>
        <td>
          <% if account.paid == '1' %>
            <i class="fas fa-check fa-2x" style="color:#3c763d;"></i>
          <% else %>
            <i class="fas fa-times fa-2x" style="color:#dd4b39;"></i>
          <% end %>
        </td>
        <td><%= account.payment_type %></td>
        <td><%= account.bank_name %></td>
        <td><%= account.check_num %></td>
        <td><%= account.date_issued %></td>
        <td><%= account.rsnum %></td>
        <td><%= account.prnum %></td>
        <td ><%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_sagad_account_path(account), :class => "btn btn-warning btn-xs" %></td>
        <td><%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, account, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/sagad/accounts/edit.html.erb
<%= render 'process' %>

app/views/sagad/accounts/get_totals.html.erb
<%= render 'totals'%>

app/views/sagad/accounts/index.html.erb
<%= render 'process' %>

app/views/sagad/accounts/new.html.erb
<%= render 'process' %>

app/views/sagad/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id client:</strong>
  <%= @account.id_client %>
</p>

<p>
  <strong>Yr:</strong>
  <%= @account.yr %>
</p>

<p>
  <strong>Mon:</strong>
  <%= @account.mon %>
</p>

<p>
  <strong>Day:</strong>
  <%= @account.day %>
</p>

<p>
  <strong>Po:</strong>
  <%= @account.po %>
</p>

<p>
  <strong>Re:</strong>
  <%= @account.re %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @account.sold %>
</p>

<p>
  <strong>Price:</strong>
  <%= @account.price %>
</p>

<p>
  <strong>Tcash:</strong>
  <%= @account.tcash %>
</p>

<p>
  <strong>Tamount:</strong>
  <%= @account.tamount %>
</p>

<p>
  <strong>Bal:</strong>
  <%= @account.bal %>
</p>

<p>
  <strong>Date paid:</strong>
  <%= @account.date_paid %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @account.paid %>
</p>

<p>
  <strong>Rsnum:</strong>
  <%= @account.rsnum %>
</p>

<p>
  <strong>Prnum:</strong>
  <%= @account.prnum %>
</p>

<p>
  <strong>Addbal:</strong>
  <%= @account.addbal %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>